--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: TourLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TourLogs" (
    "TourLogId" integer NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    "Comment" text NOT NULL,
    "Difficulty" integer NOT NULL,
    "Duration" interval NOT NULL,
    "Rating" real NOT NULL,
    "TourId" integer
);


ALTER TABLE public."TourLogs" OWNER TO postgres;

--
-- Name: TourLog_TourLogId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TourLogs" ALTER COLUMN "TourLogId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TourLog_TourLogId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tours" (
    "TourId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "FromLocation" text NOT NULL,
    "ToLocation" text NOT NULL,
    "TransportType" text,
    "TourDistance" real,
    "EstimatedTime" interval
);


ALTER TABLE public."Tours" OWNER TO postgres;

--
-- Name: Tours_TourId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tours" ALTER COLUMN "TourId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tours_TourId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: TourLogs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TourLogs" ("TourLogId", "Time", "Comment", "Difficulty", "Duration", "Rating", "TourId") FROM stdin;
12	2023-06-21 10:59:50.829+00	Wow such a cool drive! So fast too!	4	00:01:00	4	52
13	2023-06-22 11:01:29.499+00	You didn't mention the traffic jam on the motorway! I had to wait 2h!! Worst tour ever, you should be ashamed of posting it!	10	00:03:24	0	52
14	2023-06-19 11:07:48.829+00	The best walk through Vienna I know. 10/10 would walk again.	2	00:30:00	5	53
\.


--
-- Data for Name: Tours; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tours" ("TourId", "Name", "Description", "FromLocation", "ToLocation", "TransportType", "TourDistance", "EstimatedTime") FROM stdin;
52	Weekly drive	This is my weekly drive home to my hometown.	Vienna	Neusiedl am See	Car	54.9	00:41:24
53	Scenic walk in Vienna	This is a walk me and my friends like to do. It's not too long, and the buildings are just breathtaking. I hope you enjoy!	Stephansplatz 3, Vienna	Karlsplatz 10, Vienna	Walking	1.4	00:23:23
54	Brand new cycling road	The state of Vienna just finished building this new cyling road, check it out!	Vienna	Hinterbrühl	Bicycle	17.8	01:21:46
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20230317191358_Initial	8.0.0-preview.2.23128.3
\.


--
-- Name: TourLog_TourLogId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TourLog_TourLogId_seq"', 14, true);


--
-- Name: Tours_TourId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tours_TourId_seq"', 54, true);


--
-- Name: TourLogs PK_TourLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TourLogs"
    ADD CONSTRAINT "PK_TourLogs" PRIMARY KEY ("TourLogId");


--
-- Name: Tours PK_Tours; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tours"
    ADD CONSTRAINT "PK_Tours" PRIMARY KEY ("TourId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_TourLogs_TourId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TourLogs_TourId" ON public."TourLogs" USING btree ("TourId");


--
-- Name: TourLogs FK_TourLogs_Tours_TourId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TourLogs"
    ADD CONSTRAINT "FK_TourLogs_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES public."Tours"("TourId");


--
-- PostgreSQL database dump complete
--

