--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Tours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tours" (
    "TourId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "FromLocation" text NOT NULL,
    "ToLocation" text NOT NULL,
    "TransportType" text,
    "TourDistance" real,
    "EstimatedTime" timestamp with time zone
);


ALTER TABLE public."Tours" OWNER TO postgres;

--
-- Name: Tours_TourId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tours" ALTER COLUMN "TourId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tours_TourId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Tours; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tours" ("TourId", "Name", "Description", "FromLocation", "ToLocation", "TransportType", "TourDistance", "EstimatedTime") FROM stdin;
1	Tour with Database-ID 1	Mc?	Productivity	Nati's Folterkeller	\N	\N	\N
2	Tour with Database-ID 2	Mc?	Productivity	Nati's Folterkeller	\N	\N	\N
3	Tour with Database-ID 3	Mc?	Productivity	Nati's Folterkeller	\N	\N	\N
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20230317191358_Initial	8.0.0-preview.2.23128.3
\.


--
-- Name: Tours_TourId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tours_TourId_seq"', 3, true);


--
-- Name: Tours PK_Tours; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tours"
    ADD CONSTRAINT "PK_Tours" PRIMARY KEY ("TourId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

